DOCSP-43200: Get started with Django
mongodb/docs-pymongo pull request #132
Opened 2024-11-26 15:21 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-node/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2025-01-08 20:02 UTC, aclark4life requested changes
LGTM pending various small changes, thanks @norareidy

2025-01-08 20:02 UTC, aclark4life commented on snooty.toml
> +django-odm = "MongoDB Backend for Django"
`django-odm` == `django-mongodb-backend` ?

2025-01-08 20:02 UTC, aclark4life commented on source/django-get-started.txt
> +   :description: Learn how to create an app to connect to a MongoDB deployment by using Django MongoDB.
`s/Django MongoDB/Django MongoDB Backend/`

2025-01-08 20:02 UTC, aclark4life commented on source/index.txt
> +   Get Started with Django MongoDB </django-get-started>
`s/Django MongoDB/Django MongoDB Backend/`

2025-01-08 22:02 UTC, norareidy commented on snooty.toml
> +django-odm = "MongoDB Backend for Django"
Yes! The name of the source constant isn't visible - it renders as "MongoDB Backend for Django" and we just use it for writing simplicity/consistency.

2025-01-08 22:11 UTC, norareidy commented on source/django-get-started/django-connect-mongodb.txt
> +      your Atlas deployment and access the ``sample_mflix`` sample database.
The user's URI might look different, since we have them create their own - cluster, domain, etc might differ. So this would require a few different placeholders. I could just have them paste the full URI but they need to add the /sample_mflix part

2025-01-08 22:11 UTC, norareidy commented on source/django-get-started/django-connect-mongodb.txt
> +      your Atlas deployment and access the ``sample_mflix`` sample database.
I think keeping the full DATABASES setting is easier in this case

2025-01-08 22:14 UTC, norareidy commented on source/django-get-started/django-connection-string.txt
> +The connection string includes the hostname or IP address and
The URI that atlas generates doesn't include the database name, so they'd need to specify that separately (either with the NAME setting or editing the connection string)

2025-01-10 17:00 UTC, aclark4life approved these changes
LGTM, thanks

2025-01-10 19:45 UTC, norareidy commented on source/django-get-started/django-create-app.txt
> +         from django_mongodb_backend.fields import EmbeddedModelField, ArrayField
Note: the EmbeddedModelField import and the `awards` Movie field below will cause errors until [this PR](https://github.com/mongodb-labs/django-mongodb-backend/pull/151) is merged

2025-01-10 20:25 UTC, Jibola approved these changes
LGTM!!

2025-01-13 17:01 UTC, norareidy commented on source/django-get-started/django-create-admin.txt
> +site and its features, see `The Django admin site <https://docs.djangoproject.com/en/5.1/ref/contrib/admin/>`__
Updated to use the django-version-number constant

2025-01-13 18:27 UTC, norareidy commented on source/django-get-started/django-install.txt
> +         If you have already installed PyMongo and Django in your
Ah okay, deleted

2025-01-13 18:30 UTC, norareidy commented on source/django-get-started/django-write-data.txt
> +      .. code-block:: python
Our style guide advises against adding $ to bash examples, since that causes issues if the user copies and pastes directly into their terminal. I left out >>> for the same reason

2025-01-13 20:48 UTC, R-shubham commented on source/django-get-started/django-connect-mongodb.txt
> +      step of this guide.
The connection string that user copies will have username and password by default. If they are using this approach then "HOST" will expect connection string in this format: "mongodb+srv://cluster0.example.mongodb.net".  @Jibola / @aclark4life can you confirm?

2025-01-13 22:52 UTC, aclark4life commented on snooty.toml
> +django-odm = "Django MongoDB"
`s/Django MongoDB/Django MongoDB Backend/`?

2025-01-13 23:00 UTC, aclark4life commented on source/django-get-started/django-connect-mongodb.txt
> +      step of this guide.
There are at least two things going on here:

- `DATABASES["default"]["HOST"]` can accept a prefix of `mongodb+srv://` but does not require one.
- Connection string is terminology only used in the context of `parse_uri` and in that context, the MONGODB_URI from Atlas can be "cut and pasted" with the exception of the `NAME` key which is not present in the Atlas MONGODB_URI but must be present in the `parse_uri` connection string.

To put it another way:

- `DATABASES["default"]["NAME"]` must be defined. -or-
- MONGODB_URI must include `/mydatabase` e.g. `mongodb+srv://cluster0.example.mongodb.net/mydatabase`.

Again, if it's easier to steer clear of `parse_uri` for clarity's sake that's OK.

2025-01-14 01:45 UTC, timgraham commented on source/django-get-started/django-connect-mongodb.txt
> +         python3 manage.py runserver
Maybe this is consistent with the rest of your documentation and you want to leave it alone, but if you are working in a Python 3 virtual environment, you can write `python` without the 3. Coming from Django's docs, it looks odd to include that 3 on all commands.

2025-01-14 01:45 UTC, timgraham commented on source/django-get-started/django-connect-mongodb.txt
> +      .. code-block:: bash
python

2025-01-14 01:45 UTC, timgraham commented on source/django-get-started/django-connection-string.txt
> +
You may want to delete the stray blank line(s) at the end of some documents. ;-)

2025-01-14 01:45 UTC, timgraham commented on source/django-get-started/django-create-app.txt
> +             objects = MongoManager()
MongoManager isn't imported, but it's not required for this example.

2025-01-14 01:45 UTC, timgraham commented on source/django-get-started/django-create-app.txt
> +      .. code-block:: python
html+django

2025-01-14 01:45 UTC, timgraham commented on source/django-get-started/django-create-app.txt
> +      .. code-block:: python
html+django

2025-01-14 01:45 UTC, timgraham commented on source/django-get-started/django-create-app.txt
> +         python3 manage.py makemigrations sample_mflix
sample_mflix is an existing database, so the models should have an inner `Meta` class with [`managed = False`](https://docs.djangoproject.com/en/dev/ref/models/options/#managed) so that Django doesn't try to create the collections. Otherwise, I believe MongoDB will error with "collection already exists) at https://github.com/mongodb-labs/django-mongodb-backend/blob/eae01a45820de3b3a0efab4c1e85faa96335b4ad/django_mongodb_backend/schema.py#L25.

2025-01-14 01:45 UTC, timgraham commented on source/django-get-started/django-create-app.txt
> +         python3 manage.py migrate
sample_mflix is an existing database, so the models should have an inner `Meta` class with [`managed = False`](https://docs.djangoproject.com/en/dev/ref/models/options/#managed) so that Django doesn't try to create (and otherwise modify) the collections. Otherwise, I believe MongoDB will error with "collection already exists) [here](https://github.com/mongodb-labs/django-mongodb-backend/blob/eae01a45820de3b3a0efab4c1e85faa96335b4ad/django_mongodb_backend/schema.py#L25.) when running migrate...

2025-01-14 01:45 UTC, timgraham commented on source/django-get-started/django-install.txt
> +      - Django version {+django-version-number+} and its dependencies
More precisely, this will be "The latest Django 5.0.x version...'

2025-01-14 01:45 UTC, timgraham commented on source/django-get-started/django-query-data.txt
> +      .. code-block:: bash
Technically the formatter is "pycon" but since you don't format your console sessions normally, I'm not sure it matters.

2025-01-14 01:45 UTC, timgraham commented on source/django-get-started/django-write-data.txt
> +         runtime=217, released=timezone.make_aware(datetime(2020, 1, 26, 0, 0)),
`0, 0` is optional (default values)

2025-01-14 01:45 UTC, timgraham commented on source/django-get-started/django-write-data.txt
> +         movie = Movie(title="Minari", plot=
If you like, it would be more readable to format these using hanging indent, e.g. 
```
movie = Movie(
    title="Minari",
    plot="...",
    ...
)
```
Also, you can use `movie = Movie.objects.create(...)`if you want to avoid the separate `save()` step. That's the usual pattern unless you need to do something between initializing the model and saving it.

2025-01-14 02:32 UTC, aclark4life commented on source/django-get-started/django-connect-mongodb.txt
> +         python3 manage.py runserver
I was going to raise this too, but would defer to MongoDB-wide conventions. If there are no such conventions, then I prefer `python` too.

2025-01-14 12:54 UTC, aclark4life commented on source/django-get-started/django-create-app.txt
> +         python3 manage.py migrate
@timgraham As well as set `db_name` correct?

2025-01-14 14:22 UTC, timgraham commented on source/django-get-started/django-create-app.txt
> +         python3 manage.py migrate
Yes, `db_table` is already set.

2025-01-14 15:30 UTC, norareidy commented on source/django-get-started.txt
> +{+django-odm+} is a PyMongo integration that allows you to use the
Updated! Do you have a preference between "Django MongoDB Backend" and "MongoDB Backend for Django"?

2025-01-14 15:34 UTC, timgraham commented on source/django-get-started.txt
> +{+django-odm+} is a PyMongo integration that allows you to use the
The other backends I've written use the latter phrasing, however, since we had to rename our package from django-mongondb to django-mongodb-backend, we can use the former.

2025-01-14 15:37 UTC, norareidy commented on source/django-get-started/django-query-data.txt
> +      .. code-block:: bash
pycon is not an option for the .. code-block:: directive unfortunately

2025-01-17 17:00 UTC, gmiller-mdb approved these changes
LGTM!

2025-01-21 22:56 UTC, norareidy commented
Moved to the new docs-django PR: https://github.com/mongodb/docs-django/pull/10

2025-01-21 22:56 UTC, closed without merging

2025-01-22 15:09 UTC, R-shubham reviewed
LGTM