DOCSP-37500 - Tools
mongodb/docs-pymongo pull request #58
Opened 2024-04-02 19:04 UTC by mongoKart

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-node/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-37500
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37500-tools/tools/

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-04-02 19:05 UTC, mongoKart commented on source/tools.txt
> +Third-Party Tools
Is this title good?

2024-04-02 20:03 UTC, jordan-smith721 requested changes
Just a few things

2024-04-02 21:23 UTC, mongoKart commented on source/tools.txt
>  ORM-like Layers
good call

2024-04-02 21:25 UTC, mongoKart commented on source/tools.txt
All the links worked for me; was it this one?

http://blog.pythonisito.com/2009/12/ming-01-released-python-library-for.html

2024-04-02 21:29 UTC, mongoKart commented on source/tools.txt
Interesting--I don't see that message. Updated because the GitHub repo uses the link you included.

2024-04-02 21:30 UTC, mongoKart commented on source/tools.txt
>  ORM-like Layers
good call

2024-04-05 13:48 UTC, jordan-smith721 commented on source/tools.txt
Yeah but looks like it's working now

2024-04-05 13:48 UTC, jordan-smith721 approved these changes
LGTM

2024-04-08 19:35 UTC, mongoKart commented
> Two bits of feedback from https://jira.mongodb.org/browse/PYTHON-4327:
> 
> * We should remove PyMODM as it is no longer maintained.
> * We should add that all of the tools listed except for `motor` are community-maintained.

Added a note about community maintenance, but I don't see PyMODM on this page; does it have a different name now?

2024-04-08 23:22 UTC, blink1073 commented
> Added a note about community maintenance, but I don't see PyMODM on this page; does it have a different name now?

Ah, you had already removed the full "No longer maintained" section.

2024-04-08 23:22 UTC, blink1073 approved these changes
Thanks!

2024-04-09 13:29 UTC, merged