DOCSP-37540/1/9 Limit, Sort, Skip
mongodb/docs-pymongo pull request #66
Opened 2024-04-08 20:17 UTC by jordan-smith721

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-node/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-37540
https://jira.mongodb.org/browse/DOCSP-37541
https://jira.mongodb.org/browse/DOCSP-37549

Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-37540-limit/read/specify-documents-to-return/

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-04-08 21:01 UTC, mongoKart requested changes
Nice job knocking these out together!

2024-04-08 21:01 UTC, mongoKart commented on source/read/specify-documents-to-return.txt
> +options in the ``find()`` method. The following example specifies the
S:

```suggestion
You can also limit, sort, and skip results by using parameters of
the ``find()`` method. The following example specifies the
```

2024-04-09 14:28 UTC, jordan-smith721 commented on source/read/specify-documents-to-return.txt
> +You can also apply ``limit``, ``sort`` and ``skip`` by specifying them as
Pretty sure my brain must have been translating backticks into commas in this PR

2024-04-09 14:32 UTC, mongoKart approved these changes
LGTM. Nice job!

2024-04-09 20:28 UTC, blink1073 approved these changes
LGTM!

2024-04-09 21:25 UTC, merged