DOCSP-37514 - UUIDs
mongodb/docs-pymongo pull request #75
Opened 2024-04-12 13:55 UTC by mongoKart

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-node/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-37514
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37514-uuid/data-formats/uuid/

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-04-18 16:45 UTC, jordan-smith721 requested changes
Really nice job on a weird page type like this. Left a few suggestions and questions that I think could clean things up a bit. Let me know if you want to discuss formatting or anything like that

2024-04-18 19:52 UTC, mongoKart commented on source/data-formats/uuid.txt
> +UUID values of subtype 3. These legacy UUIDs can result in highly unintuitive behavior,
good catch

2024-04-18 19:53 UTC, mongoKart commented on source/data-formats/uuid.txt
> +Example: Applications Share a MongoDB Deployment
i'm in favor of almost anything that makes this page shorter

2024-04-18 19:54 UTC, mongoKart commented on source/data-formats/uuid.txt
> +Example: Applications Share a MongoDB Deployment
For some context, there were originally two of these example sections (one's now obsolete), which made more sense.

2024-04-18 19:58 UTC, mongoKart commented on source/data-formats/uuid.txt
> +     - Default?
Also removed heading colons, since it turns out those are against the SG

2024-04-18 20:00 UTC, mongoKart commented on source/data-formats/uuid.txt
> +To do so, the code performs the following steps:
I'm actually in favor of keeping this. I feel like it connects this sentence with the previous one

2024-04-18 20:05 UTC, mongoKart commented on source/data-formats/uuid.txt
> +- The UUID was inserted by an application using {+driver-short+}.
I _think_ so

2024-04-19 14:44 UTC, jordan-smith721 approved these changes
LGTM w/ one fix

2024-04-19 14:44 UTC, jordan-smith721 commented on source/data-formats/uuid.txt
> +   Use caution when working storing or retrieving UUIDs of subtype 3.
```suggestion
   Use caution when storing or retrieving UUIDs of subtype 3. 
```

2024-04-19 15:07 UTC, mongoKart commented on source/data-formats/uuid.txt
> +   Use caution when working storing or retrieving UUIDs of subtype 3.
doh

2024-04-20 01:22 UTC, blink1073 approved these changes
LGTM!

2024-04-22 14:39 UTC, merged